### ISSUE TITLE
[Feature Request / Question] Support for AUTOINCREMENT

### ISSUE THREAD

**Issue by termermc** [rehartmann/nimternalsql#1]
This is a very useful packet that I am currently using in one of my projects. I however have an issue, and that is a lack of support for AUTOINCREMENT. To increment IDs, I have to create a table to keep track of it, which is not ideal. Is there any support planned for this, or a better workaround available? Thanks.

**Comment by rehartmann** [comment]
I did not think of autoincrement but it seems like a useful feature and not very hard to implement. I'm currently investigating how to implement it.

**Comment by termermc** [comment]
It's not such a big thing but it is very helpful having the ability to do it. Otherwise, a table keeping track of the next ID has to be maintained, which adds some complexity. Thanks.

**Comment by rehartmann** [comment]
AUTOINCREMENT is implemented on the main branch. It is supported for INTEGER and BIGINT columns. it is not restricted to key columns.
